Optimization:
  n_opt: 15
  n_expl: 3

Ranges:
  f_zdt2: [[0.0], [1.0]]
  f_zdt1: [[0.0], [1.0]]
  fon: [[-4.0], [4.0]]

Shifts:
  f_zdt2: [0.9, 1.2, 1.5, 2.0]
  f_zdt1: [0.9, 1.2, 1.5, 2.0]
  fon: [0.5, 0.9, -0.5, -0.2]